[package]
name = "avenix"
version = "0.2.0"
edition = "2024"
description = "A rust ecs engine."
readme = "README.md"
repository = "https://github.com/ArjitSinghLodhi/avenix"
license = "MIT OR Apache-2.0"
keywords = ["ecs", "archetype", "simulation", "parallel"]
categories = ["development-tools"]

[dependencies]
avenix_macros = "0.1.2"
fxhash = "0.2.1"
indexmap = "2.14.1"
rayon = "1.12.0"
orx-concurrent-bag = "4.0.1"
parking_lot = "0.12.5"
dashmap = {version = "6.2.1", default-features = false, features = ["raw-api"]}

[dev-dependencies]
criterion = "0.8.2"
rusty-fork = "0.3.1"

[features]
default = []
reactivity = []
events = []

[lib]
name = "avenix"
path = "src/lib.rs"

[[test]]
name = "ecs_tests"
path = "tests/ecs_tests.rs"

[[test]]
name = "event_tests"
path = "tests/event_tests.rs"
required-features = ["events"]

[[test]]
name = "derive_test"
path = "tests/derive_tests.rs"

[[test]]
name = "change_track_test"
path = "tests/changed_tracking_test.rs"
required-features = ["reactivity"]

[[test]]
name = "added_tracking_test"
path = "tests/added_tracking_test.rs"
required-features = ["reactivity"]

[[test]]
name = "removed_tracking_test"
path = "tests/removed_tracking_test.rs"
required-features = ["reactivity"]

[[example]]
name = "hello_world"
path = "examples/01_hello_world.rs"

[[example]]
name = "commands"
path = "examples/02_commands.rs"

[[example]]
name = "parallel_commands"
path = "examples/03_parallel_commands.rs"

[[example]]
name = "events"
path = "examples/04_events.rs"
required-features = ["events"]

[[example]]
name = "parallel_events"
path = "examples/05_parallel_events.rs"
required-features = ["events"]

[[example]]
name = "query"
path = "examples/06_query.rs"

[[example]]
name = "query_parallel"
path = "examples/07_query_parallel.rs"

[[example]]
name = "query_lookups"
path = "examples/08_query_lookups.rs"

[[example]]
name = "query_reactivity"
path = "examples/09_query_reactivity.rs"
required-features = ["reactivity"]

[[example]]
name = "derive"
path = "examples/10_derive.rs"

[[example]]
name = "hierarchy_cleanup"
path = "examples/despawning/hierarchy_cleanup.rs"

[[bench]]
name = "query_lookups_fragmented"
path = "benches/query_lookups_fragmented.rs"
harness = false

[[bench]]
name = "query_lookups_fragmented_heavy"
path = "benches/query_lookups_fragmented_heavy.rs"
harness = false

[[bench]]
name = "query_lookups"
path = "benches/query_lookups.rs"
harness = false

[[bench]]
name = "query_lookups_heavy"
path = "benches/query_lookups_heavy.rs"
harness = false

[[bench]]
name = "query_simple_iter"
path = "benches/query_simple_iter.rs"
harness = false

[[bench]]
name = "query_fragmented_iter"
path = "benches/query_fragmented_iter.rs"
harness = false

[[bench]]
name = "query_write_pure"
path = "benches/query_write_pure.rs"
harness = false

[[bench]]
name = "query_write_reactive_untracked"
path = "benches/query_write_reactive_untracked.rs"
harness = false
required-features = ["reactivity"]

[[bench]]
name = "query_write_reactive_tracked"
path = "benches/query_write_reactive_tracked.rs"
harness = false
required-features = ["reactivity"]
